//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empId { get; set; }
        public string fNmae { get; set; }
        public string lName { get; set; }
        public int startWorkYear { get; set; }
        public int departmentId { get; set; }
    }
}
