//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int sid { get; set; }
        public System.DateTime date { get; set; }
        public int startTime { get; set; }
        public int endTime { get; set; }
    }
}
